ci:
  autofix_commit_msg: "style(pre-commit): autofix"

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-merge-conflict

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.0
  hooks:
    - id: clang-format
      types_or: [c++, c, cuda]

- repo: https://github.com/cpplint/cpplint
  rev: 1.6.1
  hooks:
    - id: cpplint
      args: [--quiet]
      exclude: .cu

- repo: local
  hooks:
    - id: prettier-svg
      name: prettier svg
      description: Apply Prettier with plugin-xml to svg.
      entry: prettier --write --list-different --ignore-unknown --print-width 200 --xml-self-closing-space false --xml-whitespace-sensitivity ignore
      language: node
      files: .svg$
      additional_dependencies: [prettier@2.7.1, "@prettier/plugin-xml@2.2.0"]